language: node_js
sudo: false
node_js:
  - 8
  - 9
  - 10

cache: npm

before_install: npm i -g npm@latest
install: npm ci

deploy:
  provider: npm
  skip-cleanup: true
  email: "nikeee@outlook.com"
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
    node: 10
