language: node_js
sudo: false
node_js:
  - stable
  - node

cache: npm

install: npm ci

deploy:
  provider: npm
  skip-cleanup: true
  email: "nikeee@outlook.com"
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
    node: node
